# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImagesUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    current_img = 1
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(
            "QMainWindow {\n"
            "    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
            "                                stop:0 #0C969C,  /*Top */\n"
            "                                stop:0.5 #0A7075,   /* Center */\n"
            "                                stop:1 #032F30);       /* Buttom */\n"
            "}\n"
            ""
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_CurrentImg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CurrentImg.setGeometry(QtCore.QRect(100, 30, 500, 500))
        self.lbl_CurrentImg.setStyleSheet("")
        self.lbl_CurrentImg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_CurrentImg.setText("")
        self.lbl_CurrentImg.setPixmap(QtGui.QPixmap("imagesHQ/001.png"))
        self.lbl_CurrentImg.setScaledContents(True)
        self.lbl_CurrentImg.setObjectName("lbl_CurrentImg")

        self.btn_Prev = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pressed_button("prev"))
        self.btn_Prev.setGeometry(QtCore.QRect(20, 550, 180, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Prev.setFont(font)
        self.btn_Prev.setStyleSheet(
            "QPushButton#btn_Prev {\n"
            "    border-radius: 30px;\n"
            "    background-color: #6BA3BE; \n"
            "    padding: 10px; \n"
            "    color: white;\n"
            "}\n"
            "\n"
            "QPushButton:hover#btn_Prev{\n"
            "    background-color: #031716;\n"
            "    color: white;\n"
            "}"
        )
        self.btn_Prev.setObjectName("btn_Prev")

        self.btn_Next = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pressed_button("next"))
        self.btn_Next.setGeometry(QtCore.QRect(480, 550, 180, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Next.setFont(font)
        self.btn_Next.setStyleSheet(
            "QPushButton#btn_Next {\n"
            "    border-radius: 30px;\n"
            "    background-color: #6BA3BE; \n"
            "    padding: 10px; \n"
            "    color: white;\n"
            "}\n"
            "\n"
            "QPushButton:hover#btn_Next{\n"
            "    background-color: #031716;\n"
            "    color: white;\n"
            "}"
        )
        self.btn_Next.setObjectName("btn_Next")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PokeIMG"))
        self.btn_Prev.setText(_translate("MainWindow", "PREVIOUS"))
        self.btn_Next.setText(_translate("MainWindow", "NEXT"))
    
    def pressed_button(self, which_button):
        if which_button == "next":
            self.current_img += 1
        elif which_button == "prev":
            self.current_img -= 1

        if self.current_img > 905:
            self.current_img = 1
        elif self.current_img < 1:
            self.current_img = 905

        which_img = "{:03d}".format(self.current_img)
        print(f"Button Pressed: {which_button}")
        print(f"Current Image: {which_img}")
        self.update_img(which_img+".png")
    
    def update_img(self, newImg):
        print(f"Update Img to: {newImg}")
        self.lbl_CurrentImg.setPixmap(QtGui.QPixmap(f"imagesHQ/{newImg}"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
